//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseTracker.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique number.
        /// </summary>
        public static string aa {
            get {
                return ResourceManager.GetString("aa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attorney.
        /// </summary>
        public static string Attorney {
            get {
                return ResourceManager.GetString("Attorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Role.
        /// </summary>
        public static string CaseRole {
            get {
                return ResourceManager.GetString("CaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to select an existing.
        /// </summary>
        public static string click_to_select_an_existing {
            get {
                return ResourceManager.GetString("click_to_select_an_existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to type new.
        /// </summary>
        public static string click_to_type_new {
            get {
                return ResourceManager.GetString("click_to_type_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of assignment.
        /// </summary>
        public static string Date_Assignment {
            get {
                return ResourceManager.GetString("Date_Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of return.
        /// </summary>
        public static string Date_return {
            get {
                return ResourceManager.GetString("Date_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of service.
        /// </summary>
        public static string Date_Service {
            get {
                return ResourceManager.GetString("Date_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of submission.
        /// </summary>
        public static string Date_Submission {
            get {
                return ResourceManager.GetString("Date_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string Document_Type {
            get {
                return ResourceManager.GetString("Document_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserved, Waiting for new address.
        /// </summary>
        public static string dr_Anepidoto_Anamoni_Neas_Address {
            get {
                return ResourceManager.GetString("dr_Anepidoto_Anamoni_Neas_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserved - Deceased.
        /// </summary>
        public static string dr_Anepidoto_Apeviose {
            get {
                return ResourceManager.GetString("dr_Anepidoto_Apeviose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserved - Expat.
        /// </summary>
        public static string dr_Anepidoto_Katoikos_Eksoterikou {
            get {
                return ResourceManager.GetString("dr_Anepidoto_Katoikos_Eksoterikou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unserved - Wrong Address.
        /// </summary>
        public static string dr_Anepidoto_Lathos_Address {
            get {
                return ResourceManager.GetString("dr_Anepidoto_Lathos_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Door Post.
        /// </summary>
        public static string dr_Apli_Thirokolisi {
            get {
                return ResourceManager.GetString("dr_Apli_Thirokolisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Served.
        /// </summary>
        public static string dr_Epidosi {
            get {
                return ResourceManager.GetString("dr_Epidosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancallation (Simple Door Post).
        /// </summary>
        public static string dr_Mataiosi_AM_Apli_Thirokolisi {
            get {
                return ResourceManager.GetString("dr_Mataiosi_AM_Apli_Thirokolisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation (Served).
        /// </summary>
        public static string dr_Mataiosi_AM_Epidosi {
            get {
                return ResourceManager.GetString("dr_Mataiosi_AM_Epidosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation (Full Door Post).
        /// </summary>
        public static string dr_Mataiosi_AM_Pliris_Thirokolisi {
            get {
                return ResourceManager.GetString("dr_Mataiosi_AM_Pliris_Thirokolisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cessation of activities.
        /// </summary>
        public static string dr_Pausi_Ergasion {
            get {
                return ResourceManager.GetString("dr_Pausi_Ergasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Door Posting.
        /// </summary>
        public static string dr_Pliris_Thirokolisi {
            get {
                return ResourceManager.GetString("dr_Pliris_Thirokolisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string dt_Agogi {
            get {
                return ResourceManager.GetString("dt_Agogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string dt_Aitisi {
            get {
                return ResourceManager.GetString("dt_Aitisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for Parole.
        /// </summary>
        public static string dt_Aitisi_Anastolis {
            get {
                return ResourceManager.GetString("dt_Aitisi_Anastolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposition.
        /// </summary>
        public static string dt_Anakopi {
            get {
                return ResourceManager.GetString("dt_Anakopi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court Decision for Command.
        /// </summary>
        public static string dt_Apofasi_Pros_Epitagi {
            get {
                return ResourceManager.GetString("dt_Apofasi_Pros_Epitagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court Decision for Notification.
        /// </summary>
        public static string dt_Apofasi_Pros_Gnosi {
            get {
                return ResourceManager.GetString("dt_Apofasi_Pros_Gnosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string dt_Diafora {
            get {
                return ResourceManager.GetString("dt_Diafora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Payment Notice.
        /// </summary>
        public static string dt_Diatagi_Apodosis_Xrisis_Misthiou {
            get {
                return ResourceManager.GetString("dt_Diatagi_Apodosis_Xrisis_Misthiou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order for Payment.
        /// </summary>
        public static string dt_Diatagi_Pliromis {
            get {
                return ResourceManager.GetString("dt_Diatagi_Pliromis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeal.
        /// </summary>
        public static string dt_Efesi {
            get {
                return ResourceManager.GetString("dt_Efesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Document.
        /// </summary>
        public static string dt_Eggrafo_Timologiou {
            get {
                return ResourceManager.GetString("dt_Eggrafo_Timologiou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Court.
        /// </summary>
        public static string dt_Eksodiko {
            get {
                return ResourceManager.GetString("dt_Eksodiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Disclosure.
        /// </summary>
        public static string dt_Gnostopoiisi_Martyron {
            get {
                return ResourceManager.GetString("dt_Gnostopoiisi_Martyron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoning.
        /// </summary>
        public static string dt_Klisi {
            get {
                return ResourceManager.GetString("dt_Klisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Provincial Server.
        /// </summary>
        public static string dt_Perilipsi_Epimeliti_Eparxeias {
            get {
                return ResourceManager.GetString("dt_Perilipsi_Epimeliti_Eparxeias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records of .
        /// </summary>
        public static string dt_Praktiko_Anavolis {
            get {
                return ResourceManager.GetString("dt_Praktiko_Anavolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string dt_Prosfygi {
            get {
                return ResourceManager.GetString("dt_Prosfygi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Incremental number is taken by another case.
        /// </summary>
        public static string DuplicateAA {
            get {
                return ResourceManager.GetString("DuplicateAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card number.
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not finished.
        /// </summary>
        public static string NotFinished {
            get {
                return ResourceManager.GetString("NotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable.
        /// </summary>
        public static string Payable {
            get {
                return ResourceManager.GetString("Payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro benefits are activated.
        /// </summary>
        public static string ProActivated {
            get {
                return ResourceManager.GetString("ProActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to a case, select Details and click Print.
        /// </summary>
        public static string ProMessage {
            get {
                return ResourceManager.GetString("ProMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecution.
        /// </summary>
        public static string Prosecution {
            get {
                return ResourceManager.GetString("Prosecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of service.
        /// </summary>
        public static string Result_Service {
            get {
                return ResourceManager.GetString("Result_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role type.
        /// </summary>
        public static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son of.
        /// </summary>
        public static string SonOf {
            get {
                return ResourceManager.GetString("SonOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string This_field_is_required {
            get {
                return ResourceManager.GetString("This_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Phone.
        /// </summary>
        public static string WorkPhone {
            get {
                return ResourceManager.GetString("WorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone A.
        /// </summary>
        public static string ZoneA {
            get {
                return ResourceManager.GetString("ZoneA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone B.
        /// </summary>
        public static string ZoneB {
            get {
                return ResourceManager.GetString("ZoneB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone C.
        /// </summary>
        public static string ZoneC {
            get {
                return ResourceManager.GetString("ZoneC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Cost after Taxes.
        /// </summary>
        public static string ZoneCostClean {
            get {
                return ResourceManager.GetString("ZoneCostClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Cost pre Taxes.
        /// </summary>
        public static string ZoneCostFull {
            get {
                return ResourceManager.GetString("ZoneCostFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone D.
        /// </summary>
        public static string ZoneD {
            get {
                return ResourceManager.GetString("ZoneD", resourceCulture);
            }
        }
    }
}
